apiVersion: v1
kind: Service
metadata:
  name: spring-modular-monolith-zipkin-svc
spec:
  type: NodePort
  selector:
    app: spring-modular-monolith-zipkin-pod
  ports:
    - name: zipkin-port-mapping
      port: 9411
      targetPort: 9411
      protocol: TCP
      nodePort: 30092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-modular-monolith-zipkin-deployment
spec:
  selector:
    matchLabels:
      app: spring-modular-monolith-zipkin-pod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: spring-modular-monolith-zipkin-pod
    spec:
      containers:
        - name: zipkin
          image: "openzipkin/zipkin:3.4.4"
          ports:
            - name: zipkin
              containerPort: 9411
          env:
            - name: STORAGE_TYPE
              value: mem
